services:
  EXSyst\DynamicClassGenerationBundle\Compiler\ChainClassInvalidator:
    arguments:
      $invalidators: ~
    autowire: false
    autoconfigure: false
    public: false
    lazy: true

  EXSyst\DynamicClassGenerationBundle\Compiler\ClassGeneratorInterface:
    alias: EXSyst\DynamicClassGenerationBundle\Compiler\TemporaryWrappedClassGenerator

  EXSyst\DynamicClassGenerationBundle\Compiler\ClassInvalidatorInterface:
    alias: EXSyst\DynamicClassGenerationBundle\Compiler\ChainClassInvalidator

  EXSyst\DynamicClassGenerationBundle\Compiler\ClassResolver:
    arguments:
      $cacheDirectory: '%exsyst_dynamic_class_generation.cache_directory%'
      $prefixes: '%exsyst_dynamic_class_generation.resolver_prefix_tree%'
    autowire: false
    autoconfigure: false
    public: false

  EXSyst\DynamicClassGenerationBundle\Compiler\DispatchClassGenerator:
    arguments:
      $generators: ~
    autowire: false
    autoconfigure: false
    public: false

  EXSyst\DynamicClassGenerationBundle\Compiler\TemporaryWrappedClassGenerator:
    arguments:
      $generator: '@EXSyst\DynamicClassGenerationBundle\Compiler\DispatchClassGenerator'
      $temporaryDirectory: '%exsyst_dynamic_class_generation.temporary_directory%'
    autowire: false
    autoconfigure: false
    public: false
    lazy: true

  EXSyst\DynamicClassGenerationBundle\DynamicClassLoader:
    autoconfigure: false
    autowire: true
    public: true
